version: '2'
services:
  db:
    build:
      context: .
      dockerfile: ./mysql/Dockerfile
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci --skip-character-set-client-handshake
  php:
    build:
      context: .
      dockerfile: ./php/Dockerfile
    volumes:
      - .:/laradock_lite
    depends_on:
      - db
  server:
    build:
      context: .
      dockerfile: ./apache/Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - php

volumes:
  mysql_data:
    driver: 'local'
